### ISSUE TITLE
no newline in etc/tendrl/tendrl.conf.sample file

### ISSUE THREAD

**Issue by mbukatov** [Tendrl/node_agent#109]
For some reason, there is no newline character in `etc/tendrl/tendrl.conf.sample` file.

The common expectation is that [there should be a newline even in the end of the last line in a file](https://stackoverflow.com/questions/729692/why-should-text-files-end-with-a-newline).

## Reasoning

Failing on this simple requirement could make some tools to fail.

QE team is affected by this as it causes ansible `ini_file` module to mange `tendrl.conf` file during setup, so that the updated file is invalid which makes `tendrl-node-agent` crash.

Example of affected file which lacked newline after processing by ansible `ini_file` module:

```
# installation_source_type decides how tendrl will install a software
# the possible values are pip, rpm, deb.
installation_source_type = rpm[gluster_integration]
log_cfg_path = /etc/tendrl/gluster_integration_logging.yaml
```

**Comment by nnDarshan** [comment]
@mbukatov Thanks for the fix
