### ISSUE TITLE
install instructions documentation

### ISSUE THREAD

**Issue by mkudlej** [Tendrl/node_agent#2]
There should be document which describes:

what software should be installed and how should be configured before installing Tendrl
Tendrl installation process
Tendrl post installation steps like configuration, service starting and so on

[was originally at https://tendrl.atlassian.net/browse/TEN-36]

**Comment by r0h4n** [comment]
For installation from pip/source : https://github.com/Tendrl/node_agent/blob/master/doc/source/installation.rst
