### ISSUE TITLE
Document flows and atoms for node_agent related to "managed storage node"

### ISSUE THREAD

**Issue by r0h4n** [Tendrl/node_agent#3]
1. Create operational yaml file for node_agent, refer https://github.com/Tendrl/gluster_bridge/blob/master/etc/sds_operations_gluster-3.8.3.yaml 
2. Identify and document atoms (smallest possible atomic actions carried out by the node_agent), start with atoms related to  http://docs.ansible.com/ansible/list_of_all_modules.html
3. Define higher level storage node management flows (eg: install ceph, configure ceph etc) in the same operational yaml which will comprise of atoms for shell/commands, filesystem actions, packaging/system actions

**Comment by r0h4n** [comment]
Please see atom described in the file "sds_atoms_gluster-3.8.3.sample.yaml"  and define atoms for this task similarly.

For flows which will group these atoms, check the CreateVolume gluster flow in "sds_flows_gluster-3.8.3.sample.yaml"

**Comment by nnDarshan** [comment]
okay, As per https://github.com/Tendrl/gluster_bridge/pull/16/commits/44722a59d0af76cd90f7bfede573ba485a28108c#diff-f593f97c6438f19aab2e883393e3745dR10 the atoms are classified under certain types. But how to classify atoms like command, shell etc. As these atoms can be used to perform any type of action.

Also you are using <uuid.uuid4()> for uuid, should I replace with an actual UUID that I generate using python uuid.ruuid4() ? or leave it as is ?

**Comment by nnDarshan** [comment]
@r0h4n @nthomas-redhat can you please review the patch, have updated the operations and flow file. I feel these atomic operations and flows should cover almost all our requirements from node agent.

**Comment by nnDarshan** [comment]
corresponding JIRA ticket: https://tendrl.atlassian.net/browse/TEN-26
