### ISSUE TITLE
Request validator for parsing and validating given api-job requests

### ISSUE THREAD

**Issue by TimothyAsir** [Tendrl/node_agent#7]
1) Parse node operations yaml file and fetch the required details for the given request.
2) Validate the given api job request
3) provide feedback or return status.

**Comment by r0h4n** [comment]
-Operations:
--Please see atom described in the file "sds_atoms_gluster-3.8.3.sample.yaml"  and define atoms for       this task similarly.
--For flows which will group these atoms, check the CreateVolume gluster flow in "sds_flows_gluster-3.8.3.sample.yaml"  

Input api-job:
WIP (https://tendrl.atlassian.net/browse/TEN-28?focusedCommentId=10603&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-10603)

-Task
Read input api-job and extract information such as flow name from the api-job json, extract attributes from api-job json and map it with the local_inputs required for the atoms in the flow.

**Comment by r0h4n** [comment]
The requirements on this have shifted a lot, closing this
