### ISSUE TITLE
EPEL dependency for deployment via packages

### ISSUE THREAD

**Issue by fbalak** [Tendrl/node_agent#75]
Tendrl upstream rpm packages should not depend on any package from EPEL repository.
Packages required from EPEL:
- ansible
- collectd

**Comment by r0h4n** [comment]
Tendrl targets to create rpms for fedora, centos7, rhel7, I guess you are trying to say that the rhel7 rpms should not depend on EPEL?

Because using EPEL is fine for Tendrl in case of fedora or centos7

**Comment by r0h4n** [comment]
I am closing this one, EPEL things are ok in Centos or fedora
