### ISSUE TITLE
Replace deployment_type in conf file with installation_source_type

### ISSUE THREAD

**Issue by nnDarshan** [Tendrl/node_agent#83]
Currently we have a field in node-agent conf file called "deployment_type" this is used to decide the type of package installation like pip, rpm, deb.
Its better to replace it with a field called as installation_source_type, which can have values like pip, rpm, deb. Based on this we do the package installation in node-agent.

**Comment by r0h4n** [comment]
Any updates?

**Comment by nnDarshan** [comment]
@r0h4n Should I fix it right away, or wait for https://github.com/Tendrl/specifications/pull/7 and https://github.com/Tendrl/specifications/pull/11 to be closed ?

**Comment by r0h4n** [comment]
Send in a PR, we can rebase with the mentioned specs later
